import Link from 'next/link';
import { Research } from './Research';
import { Briefing, Event, labels, Result, safeUrl, time } from '@/lib/data';

export function Empty({ state }: { state: Result['state'] }) {
  return <div className="empty"><span className="eyebrow">RESEARCH DESK</span><h2>{state === 'error' ? '자료를 불러오지 못했습니다' : state === 'unconfigured' ? '리서치 서비스 준비 중' : '아직 발행된 자료가 없습니다'}</h2><p>{state === 'error' ? '잠시 후 다시 확인해 주세요. 기존 자료가 삭제된 것은 아닙니다.' : state === 'unconfigured' ? '데이터 연결이 완료되면 최신 시장 브리핑을 확인할 수 있습니다.' : '첫 브리핑 발행 후 시황과 분석이 표시됩니다. 검색 중이라면 조건을 변경해 보세요.'}</p></div>;
}
export function ReportList({ rows }: { rows: Briefing[] }) {
  return <div className="report-list">{rows.map(r => <Link className="report-link" href={`/${r.kind}?id=${r.id}`} key={r.id}><span className="eyebrow">{labels[r.kind]}</span><h3>{r.title}</h3><span className="muted">{time(r.generated_at)}</span><span className="arrow">↗</span></Link>)}</div>;
}
export function Events({ items }: { items: Event[] }) {
  return <div className="events">{items.length ? items.map((e, i) => <article key={`${e.title}-${i}`}><span className="rank">{String(i+1).padStart(2,'0')}</span><div><h3>{safeUrl(e.url || e.link) ? <a href={safeUrl(e.url || e.link)} target="_blank" rel="noopener noreferrer">{e.corp_name} {e.title} ↗</a> : e.title}</h3>{e.research_insight ? <><span className="tag">{e.research_insight.impact}</span><p><b>관측</b> {e.research_insight.fact}</p><p><b>조건부 해석</b> {e.research_insight.interpretation}</p><p><b>확인 사항</b> {e.research_insight.watchpoint}</p><small>{e.research_insight.basis}</small></> : e.why_it_matters ? <p>{e.why_it_matters}</p> : <p className="muted">원문 확인 전 영향 판단 보류</p>}<small>{e.source || e.press || '원문 참고'} · {e.published_at || e.time || '발행시각 미제공'}</small></div></article>) : <p className="muted">새로 확인된 이벤트가 없습니다.</p>}</div>;
}
function EventGroup({ label, items, collected }: { label: string; items: Event[]; collected?: number }) {
  const initial = items.slice(0, 2), remaining = items.slice(2);
  return <div className="event-group"><div className="event-group-title"><h3>{label}</h3><span>{collected ?? items.length}건 확인 · 주요 {items.length}건</span></div><Events items={initial}/>{remaining.length > 0 && <details className="event-more"><summary>{label} {remaining.length}건 더보기</summary><Events items={remaining}/></details>}</div>;
}
function Text({ value }: { value: string }) { return <>{value.split(/(\*\*.*?\*\*)/g).map((v,i) => v.startsWith('**') ? <strong key={i}>{v.slice(2,-2)}</strong> : v)}</>; }
export function Report({ row, previous, peer, comparisonError, historical = false }: { row: Briefing; previous?: Briefing; peer?: Briefing; comparisonError?: boolean; historical?: boolean }) {
  const p = row.payload, markets = p.market_signals || p.indexes || {};
  const names: Record<string,string> = { kospi:'KOSPI',kosdaq:'KOSDAQ',sp500:'S&P 500',nasdaq:'NASDAQ',dow:'DOW',ewy:'EWY',usdkrw:'USD / KRW',vix:'VIX',us10y:'미국 10년물',wti:'WTI' };
  const points = p.key_points || p.summary_items || p.next_week_outlook?.rationale || [];
  const age = Date.now() - new Date(row.generated_at).getTime();
  const old = !historical && age > (row.kind === 'live' ? 2 : row.kind === 'daily' ? 30 : 192) * 3600000;
  return <><section className="hero"><div><span className="eyebrow">{labels[row.kind]} · {p.edition_title || 'MARKET PERSPECTIVE'}</span><h1>{row.title}</h1><p className="meta">발행 {time(row.generated_at)}{historical && ' · 과거 보고서'}</p>{row.observation_end && <p className="meta">관측 종료 {time(row.observation_end)}</p>}{old && <p className="notice">최근 생성 이후 시간이 경과했습니다. 휴장·실행 일정과 지표별 기준시각을 확인하세요.</p>}</div><aside className="hero-aside"><span className="eyebrow">오늘의 관점</span><strong>{p.sentiment?.label || p.next_week_outlook?.bias || '근거 중심의 시장 점검'}</strong><p>{p.sentiment?.interpretation || '시장 변화와 주요 이벤트를 함께 살펴봅니다.'}</p>{p.sentiment && <small>시장 온도 {p.sentiment.score} / 100 · 보조 지표</small>}</aside></section>
    {Object.keys(markets).length > 0 && <section className="market-strip" aria-label="주요 시장 지표">{Object.entries(markets).map(([k,m]) => <div key={k}><span>{names[k] || k}</span><strong>{m.price}</strong><em className={/[▲+]/.test(m.change) ? 'up' : /[▼−-]/.test(m.change) ? 'down' : ''}>{m.change}</em><small>{m.market_status} · {m.as_of || '기준시각 미제공'}</small></div>)}</section>}
    <div className="reading-layout"><div className="main-column"><Research row={row} previous={previous} peer={peer} comparisonError={comparisonError}/><section><div className="section-heading"><span>01 / PERSPECTIVE</span><h2>핵심 시황</h2></div><div className="analysis">{points.length ? points.map((s,i) => /^\[.*\]$/.test(s) ? <h3 key={i}>{s.slice(1,-1)}</h3> : <p key={i}><Text value={s}/></p>) : <p>분석에 필요한 데이터가 축적 중입니다.</p>}</div></section>
    {row.kind === 'daily' && <><section><div className="section-heading"><span>02 / SECTOR FOCUS</span><h2>주목 업종</h2></div><p className="muted">뉴스·이벤트 기준 관찰 · 업종 수익률 순위가 아닙니다.</p><div className="sector-grid">{p.research?.sectors.length ? p.research.sectors.map(s => <article key={s.name}><span className="tag">{s.stance}</span><h3>{s.name}</h3><Events items={s.evidence.slice(0,1)}/></article>) : <p>업종별 근거를 확보 중입니다.</p>}</div></section>
    <section><div className="section-heading"><span>03 / STOCK WATCH</span><h2>관심 종목</h2></div>{p.research?.screening && <p className="muted">후보 {p.research.screening.universe} · 긍정 근거 {p.research.screening.evidence} · 가격 조회 {p.research.screening.quote_requested} · 조건 통과 {p.research.screening.qualified} · 최종 {p.research.stocks.length}</p>}<p className="muted">{p.research?.method || '자료가 충분한 종목만 선별합니다.'}</p>{p.research?.stocks.length ? p.research.stocks.map(s => <article className="stock" key={s.ticker}><div className="stock-header"><div><span className="eyebrow">{s.sector} · {s.status}</span><h3>{s.name} <small>{s.ticker}</small></h3></div><div><strong>{s.quote.price.toLocaleString('ko-KR')}원</strong><small>{time(s.quote.as_of)}</small></div></div><p><b>선정 근거</b> {s.reason}</p>{s.catalyst && <p><b>Catalyst · 확인할 계기</b> {s.catalyst}</p>}<p><b>주요 위험</b> {s.risk}</p><p><b>재검토 조건</b> {s.invalidation}</p><details><summary>원문 근거 확인</summary><Events items={s.evidence}/></details></article>) : <div className="quiet-box">{p.research?.empty_reason || '선정 기준을 충족하는 자료가 없습니다.'}</div>}</section></>}
    {row.kind === 'weekly' ? <><section><h2>주간 시장 변화</h2><div className="table-wrap"><table><thead><tr><th>지표</th><th>첫 관측</th><th>마지막 관측</th><th>변화</th></tr></thead><tbody>{p.market_performance?.map(m => <tr key={m.label}><td>{m.label}</td><td>{m.start}</td><td>{m.end}</td><td>{m.change_text}</td></tr>)}</tbody></table></div></section><section><h2>시장 온도 추이</h2><p className="muted">{p.summary?.trading_days || 0}일 · {p.summary?.count || 0}개 관측 · 0~100점 보조 지표</p>{p.daily_points?.map(d => <div className="trend-row" key={d.day}><span>{d.day}</span><meter min="0" max="100" value={d.score_avg} aria-label={`${d.day} 시장 온도`}/><strong>{d.score_avg.toFixed(1)}</strong></div>)}</section><section><h2>주간 기회와 위험 근거</h2><h3>기회 요인</h3><Events items={p.opportunity_events || []}/><h3>위험 요인</h3><Events items={p.risk_events || []}/></section><section><h2>다음 주 조건부 시나리오</h2><div className="scenario"><h3>기본 관점</h3><p>{p.next_week_outlook?.bias || '자료 축적 중'}</p><h3>상방 조건</h3>{p.next_week_outlook?.upside_conditions.map((s,i) => <p key={i}>{s}</p>)}<h3>하방 조건</h3>{p.next_week_outlook?.downside_conditions.map((s,i) => <p key={i}>{s}</p>)}<p className="muted">{p.next_week_outlook?.bias} · 표본 신뢰도 {p.next_week_outlook?.confidence}</p></div></section></> : <section><div className="section-heading"><span>MARKET DRIVERS</span><h2>주요 뉴스와 공시</h2></div><p className="muted">원천별로 최대 5건의 핵심 근거를 보관하며, 처음에는 우선순위 2건만 표시합니다.</p><div className="event-groups"><EventGroup label="뉴스" items={p.news_items || p.events?.news || []} collected={p.events?.news_count}/><EventGroup label="공시 (DART)" items={p.events?.dart || []} collected={p.events?.dart_count}/></div></section>}
    {safeUrl(p.cover_image) && <section><div className="section-heading"><span>EDITORIAL COMIC</span><h2>그림으로 보는 시장</h2></div>{/* eslint-disable-next-line @next/next/no-img-element */}<img className="comic" src={safeUrl(p.cover_image)} alt="이번 데일리 브리핑의 시장 분위기를 표현한 AI 만화" loading="lazy"/><p className="muted">시장 해석을 돕는 AI 생성 이미지입니다.</p></section>}</div>
    <aside className="sidebar"><section><span className="eyebrow">WATCH POINT</span><h2>다음 확인 사항</h2><p><Text value={p.watchpoint || p.summary?.top_watchpoint || '후속 공시와 시장 지표의 변화가 현재 판단을 뒷받침하는지 확인하세요.'}/></p></section><section><h3>분석 기준</h3><p>자료 발행시각과 시장 지표의 기준시각은 다를 수 있습니다.</p>{p.collection_cutoff && <p>수집 마감<br/>{time(p.collection_cutoff)}</p>}<details><summary>데이터와 해석 자세히 보기</summary><p>AI 분석 및 규칙 기반 계산 결과입니다.</p>{p.sentiment && <p>데이터 충실도 {p.sentiment.data_completeness ?? '미제공'}%</p>}<p>{p.reliability?.status}</p><p>{p.reliability?.guidance}</p></details></section><Link href="/archive">이전 보고서 찾아보기 →</Link></aside></div></>;
}
